[package]
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

[dependencies]
# There exists at least one version where buck builds this crate
ahash = "0.8.11"
allocative = "0.3.4"
anyhow = "1.0.98"
arrayvec = "0.7.6"
assert_cmd = "2.0.17"
assert_matches = "1.5.0"
async-io = "2.4.0"
async-trait = "0.1.88"
atomic = "0.6.0"
aws-types = "1.3.7"
axum = "0.8.4"
axum-core = "0.5.2"
backtrace = "0.3.74"
bigdecimal = "0.4.8"
bindgen = "0.71.1"
# bitcoin-internals = "0.4.0"
bitcoin-private = "0.1.0"
# blake3 = "1.8.2"
# blst = "0.3.14"
bytecheck = "0.8.1"
bzip2-sys = "0.1.13+1.0.8"
# camino = "1.1.9"
cc = "1.0.49"
# cedar-policy-cli = "4.4.0"
# cedar-policy-core = "4.4.0"
# cedar-policy-validator = "4.4.0"
chrono-tz = "0.10.3"
# clang-sys = "1.8.1"
clear_on_drop = "0.2.5"
# compiler_builtins = "0.1.157"
const_fn = "0.4.11"
cookie = "0.18.1"
core-foundation-sys = "0.8.7"
cpp_demangle = "0.4.4"
crc32c = "0.6.8"
crc32fast = "1.4.2"
crossbeam-epoch = "0.9.18"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
crunchy = "0.2.3"
curve25519-dalek = "4.1.3"
curve25519-dalek-ng = "4.1.1"
cxx = "1.0.158"
object = "0.36.7"
portable-atomic-util = "0.2.4"
tracing = "0.1.41"
typeid = "1.0.3"

# Commented out until figure out how to stop
# buck2 building win crates on other OSes
# [target.'cfg(windows)'.dependencies]
# winapi = "0.3.9"
