[package]
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

[dependencies]
# There exists at least one version where buck builds this crate
assert_matches = "1.5.0"
cc = "1.0.49"
mongodb = "3.2.3"
portable-atomic-util = "0.2.4"
ring_17_5 = { package = "ring", version = "=0.17.5" }
ring_16 = { package = "ring", version = "0.16" }
rust-i18n = "3.1.4"
rustc_version_runtime = "0.3.0"
tracing = "0.1.41"
typeid = "1.0.3"
winapi = "0.3.9"
