[package]
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

[dependencies]
# There exists at least one version where buck builds this crate
assert_matches = "1.5.0"
cc = "1.0.49"
object = "0.36.7"
portable-atomic-util = "0.2.4"
typeid = "1.0.3"
winapi = "0.3.9"
