#!/usr/bin/env bash
set -euo pipefail

# Mint a dated snapshot rig (third-party/snapshots/<slot>/) — an era-mirror of
# the main rig resolved against a point-in-time crates.io index. See README
# "Dated snapshots" and issue #45.
#
#   ./mint-snapshot.sh <slot> <index-branch>
#   ./mint-snapshot.sh 2025-11 snapshot-2025-10
#
# Each snapshot resolves its OWN consistent pin-set for the era: we take the
# main rig's dependency NAMES (not its pins — those are today's), float them to
# `*`, and let the frozen index pick each crate's era-latest. Crates that didn't
# exist yet at that date — or that can't be satisfied consistently — are pruned
# (logged), since an era consumer wouldn't have had them either. The committed
# Cargo.lock is the durable pin; buckify/CI never touch the index after minting.
#
# Requires: the frozen index branch in gilescope/crates.io-index (see README on
# how those are reconstructed). reindeer, cargo, buck2, python3, git on PATH.

slot="${1:?usage: mint-snapshot.sh <slot e.g. 2025-11> <index-branch e.g. snapshot-2025-10>}"
branch="${2:?missing <index-branch>}"
repo_root="$(cd "$(dirname "$0")" && pwd)"
rig="third-party/snapshots/${slot}"
index_dir="${SNAPSHOT_INDEX_DIR:-$HOME/data/crates-index-snapshots}/${slot}"
index_fork="${SNAPSHOT_INDEX_FORK:-https://github.com/gilescope/crates.io-index}"
reindeer="${REINDEER:-reindeer}"
cd "$repo_root"

# 1. Frozen index as a usable local registry. A registry can't be a shallow
#    clone (cargo refuses to update shallow roots), so flatten the single
#    fetched commit into a self-contained root commit (no remote, no shallow
#    marker). --no-verify / gpgsign=false: this throwaway repo isn't ours to
#    sign and the global hooks would reject the index's own large files.
if [ ! -d "$index_dir/.git" ]; then
  echo "▸ cloning frozen index $branch -> $index_dir"
  mkdir -p "$(dirname "$index_dir")"
  git clone -q --depth 1 --single-branch --branch "$branch" "$index_fork" "$index_dir"
  ( cd "$index_dir"
    git checkout -q --orphan flat
    git -c user.name=snap -c user.email=snap@local -c commit.gpgsign=false \
        commit -qn -m "frozen crates.io index @ $branch" >/dev/null
    git branch -q -D "$branch" 2>/dev/null || true
    git remote remove origin 2>/dev/null || true
    rm -f .git/shallow
    git symbolic-ref HEAD refs/heads/flat )
fi
# Sanity: a faithful crates.io index points its downloads at crates.io.
dl="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("dl",""))' "$index_dir/config.json")"
case "$dl" in
  *crates.io*) ;;
  *) echo "✗ $index_dir is not a faithful crates.io index (dl=$dl)"; exit 1 ;;
esac

cargo_cfg=(--config 'source.crates-io.replace-with="frozen"'
           --config "source.frozen.registry=\"file://$index_dir\"")

# 2. main rig dep NAMES, floated to `*` (carry features + default-features;
#    skip the exact-pinned crates whose fixups embed a fixed version/symbol).
mkdir -p "$rig/top"
printf '// Dummy source to keep Cargo happy\n\nfn main() {}\n' > "$rig/top/main.rs"
cat > "$rig/reindeer.toml" <<'EOF'
# Dated snapshot rig: reuse the repo's own fixups/ via shared_fixups (searched
# after this rig's local fixups/), so a crate only carries a local override here
# where its build differs at this snapshot's resolved version. Requires a
# reindeer with shared_fixups support (facebookincubator/reindeer#107).
shared_fixups = ["../../../fixups"]
EOF

# Local overrides for fixups that can't be shared into a snapshot. librocksdb-sys's
# shared fixup maps an `overlay` of vendored rocksdb C++ by path; at the snapshot's
# depth reindeer emits `../../../fixups/...`, which buck2 rejects as an un-normalized
# source path and refuses to PARSE the rig. Stub it (run=false, no overlay) so the
# rig parses; the crate then fails to build and is tracked in expected-failures.
mkdir -p "$rig/fixups/librocksdb-sys"
cat > "$rig/fixups/librocksdb-sys/fixups.toml" <<'EOF'
# See mint-snapshot.sh: the shared librocksdb-sys overlay can't normalize at this
# depth, so it's stubbed here. librocksdb-sys then fails to build (expected).
buildscript.run = false
EOF
python3 - "$slot" "$branch" > "$rig/Cargo.toml" <<'PYEOF'
import tomllib, sys
slot, branch = sys.argv[1], sys.argv[2]
deps = tomllib.loads(open("third-party/Cargo.toml").read())["dependencies"]
SKIP = {"ring", "matchit_v8"}  # exact-pinned: fixup embeds a fixed version/symbol
print(f'''# Dated version-set rig: the crates.io constellation as it resolved in the
# "{slot}" NixOS-style slot, minted against a frozen index (gilescope/
# crates.io-index branch {branch}) so every dep resolves to its era-latest.
# Generated by mint-snapshot.sh from the main rig's dep set — DO NOT hand-edit;
# re-mint instead. See README "Dated snapshots" and issue #45.
#
# Deps are `*`: the committed Cargo.lock is the era pin (mint-once, commit-lock).
# Re-minting requires the time machine; a plain `cargo generate-lockfile` would
# resolve TODAY's versions and defeat the snapshot. Crates absent at this date
# (or unsatisfiable in a consistent set) were pruned at mint time.
#
# [workspace] pins this as its own root so cargo never walks into the main rig.
[workspace]
resolver = "2"

[package]
name = "rust-third-party-snapshot-{slot}"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "top"
path = "top/main.rs"

[dependencies]''')
for k, v in sorted(deps.items()):
    if k in SKIP:
        continue
    feats = v.get("features") if isinstance(v, dict) else None
    nodef = isinstance(v, dict) and v.get("default-features") is False
    if feats or nodef:
        parts = ['version = "*"']
        if nodef:
            parts.append("default-features = false")
        if feats:
            parts.append("features = " + repr(feats).replace("'", '"'))
        print(f'{k} = {{ {", ".join(parts)} }}')
    else:
        print(f'{k} = "*"')
PYEOF

# 3. Prune to a consistent era set: cargo metadata is what reindeer parses, so
#    drive the loop off it. Drop the crate named by each resolvable failure
#    class (absent at date / missing feature / unsatisfiable version) and retry.
echo "▸ resolving consistent era set for $slot (this prunes crates absent at $branch)"
dropped=""
for _ in $(seq 1 500); do
  rm -f "$rig/Cargo.lock"
  err="$(cargo metadata --format-version 1 --manifest-path "$rig/Cargo.toml" \
         "${cargo_cfg[@]}" 2>&1 >/dev/null)" && break
  # single quotes: backticks are literal (matching cargo's text), \1 must not expand
  # shellcheck disable=SC2016
  crate="$(printf '%s\n' "$err" | sed -n \
    -e 's/.*no matching package named `\([^`]*\)`.*/\1/p' \
    -e 's/.*depends on `\([^`]*\)` with feature.*/\1/p' \
    -e 's/.*failed to select a version for the requirement `\([^ ]*\) .*/\1/p' \
    -e 's/.*failed to select a version for `\([^`]*\)`.*/\1/p' | head -1)"
  if [ -z "$crate" ]; then
    echo "✗ unhandled resolution error for $slot:"; printf '%s\n' "$err" | grep -iE 'error' | head -8
    exit 1
  fi
  # only prune direct deps; a transitive-only conflict means our set is wrong
  grep -qE "^${crate} = " "$rig/Cargo.toml" || {
    echo "✗ conflict on transitive crate '$crate' (not a direct dep) for $slot:"; printf '%s\n' "$err" | head -8
    exit 1; }
  sed -i.bak -E "/^${crate} = /d" "$rig/Cargo.toml" && rm -f "$rig/Cargo.toml.bak"
  dropped="$dropped $crate"
done
# Final authoritative lock.
cargo generate-lockfile --manifest-path "$rig/Cargo.toml" "${cargo_cfg[@]}" >/dev/null 2>&1
pkgs="$(python3 -c 'import tomllib;print(len(tomllib.loads(open("'"$rig"'/Cargo.lock").read())["package"]))')"
[ -n "${dropped# }" ] && echo "  pruned (absent/inconsistent at $branch):$dropped"
echo "  resolved $pkgs packages"

# 4. Buckify; surface any silent-build-script gaps (the rot #45 hunts — each
#    needs a version-gated buildscript directive in the shared fixup).
echo "▸ buckify $rig"
out="$("$reindeer" --third-party-dir "$rig" buckify 2>&1)" || {
  echo "✗ buckify failed:"; printf '%s\n' "$out" | tail -20; exit 1; }
if [ -n "$out" ]; then
  echo "⚠ buckify gaps to fix (version-gate buildscript.run in the shared fixup):"
  printf '%s\n' "$out" | sed -E 's/.*fixups\] /  /'
else
  echo "◈ $slot: buckify clean"
fi
