# MIT / Apache-2.0 https://github.com/crates-pro/crates-pro-infra/tree/main/third-party/fixups
rustc_flags = [
    "-Lnative=$(location :libgit2-sys-0.18.0+1.9.0-build-script-run[out_dir])/build",
    "-lstatic=git2",
]

[buildscript.run.env]
OPT_LEVEL = "3"
