# Apache 2.0 from https://github.com/systeminit/si/tree/main/third-party/rust
[[cxx_library]]
name = "libsodium"
srcs = ["libsodium/src/**/*.c"]
headers = ["libsodium/src/**/*.h"]
include_paths = [
  "libsodium/src/libsodium/include",
  "libsodium/src/libsodium/include/sodium",
]
fixup_include_paths = [
  "include",
]
