extra_srcs = ["README.md", "md_doc/**/*.md"]

['cfg(target_os = "macos")']
rustc_flags = [
  "-lframework=IOKit",
  "-lframework=Foundation",
  "-lframework=CoreFoundation",
  "-lframework=DiskArbitration",
]
