name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
      branches: [ '**' ]

jobs:
  run:
    name: CI
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0  # Full clone so we can diff against main

      - name: Install Buck2
        uses: dtolnay/install-buck2@latest

      - name: Download reindeer
        run: |
          wget -q https://github.com/facebookincubator/reindeer/releases/download/v2025.04.30.00/reindeer-x86_64-unknown-linux-gnu.zst

      - name: Install reindeer
        run: |
          zstd -d ./reindeer-x86_64-unknown-linux-gnu.zst -o ./reindeer
          chmod +x ./reindeer
          sudo ln -s "$PWD/reindeer" /usr/local/bin/reindeer

      - name: Run build
        run: |
          ./test.sh
