# Apache 2.0 from https://github.com/thoughtpolice/qq

buildscript.run = false
cargo_env = true

[['cfg(all(target_os = "windows"))'.cxx_library]]
name = "cbits-windows"
srcs = ["src/arch/windows.c"]
include_paths = ["src/arch"]
preferred_linkage = "static"
